def f():
    x= "local"
    print("x is inside:",x)

f()
#if we try to call oustide the function it will show error.